local PrototypeConfig = {
    GuardianMarkerFolderName = "GuardianMarkers",
    ProfilesBySpawnPointID = {
        ["Regular/Spawn04"] = {
            ProfileName = "LightGuardedRegular",
            IceType = "Regular",
            SpawnMarkerName = "Spawn04",
            GuardianCount = 1,
        },
        ["Thick/Spawn03"] = {
            ProfileName = "MediumGuardedThick",
            IceType = "Thick",
            SpawnMarkerName = "Spawn03",
            GuardianCount = 2,
        },
        ["Thick/Spawn04"] = {
            ProfileName = "HeavyGuardedThick",
            IceType = "Thick",
            SpawnMarkerName = "Spawn04",
            GuardianCount = 3,
        },
    },
}

return PrototypeConfig
