local RegionConfig = {
    Snowfield = {
        DisplayName = "SNOWFIELD",
        RecommendedWarmth = 100,
        ColdMultiplier = 1,
    },
    FrozenPass = {
        DisplayName = "FROZEN PASS",
        RecommendedWarmth = 1000,
        ColdMultiplier = 10,
    },
    AncientExpanse = {
        DisplayName = "ANCIENT EXPANSE",
        RecommendedWarmth = 10000,
        ColdMultiplier = 100,
    },
    BlackIceHollow = {
        DisplayName = "BLACK ICE HOLLOW",
        RecommendedWarmth = 100000,
        ColdMultiplier = 1000,
    },
    MeteorReach = {
        DisplayName = "METEOR REACH",
        RecommendedWarmth = 1000000,
        ColdMultiplier = 10000,
    },
}

return RegionConfig
